# Generated by Django 3.2.9 on 2022-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('drink', models.CharField(max_length=200)),
                ('extra', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('voucher', models.BooleanField(default=False)),
            ],
        ),
    ]
