# Generated by Django 3.2.9 on 2022-05-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('food_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('extra_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('drink_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurant.order')),
            ],
        ),
    ]
